# Generated by Django 3.0 on 2022-07-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='numero_cada',
            new_name='numero_casa',
        ),
    ]
